# Generated by Django 3.2.23 on 2024-05-28 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileId', models.AutoField(primary_key=True, serialize=False)),
                ('profileName', models.CharField(max_length=15)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagId', models.AutoField(primary_key=True, serialize=False)),
                ('tagName', models.CharField(max_length=255)),
                ('profileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folderId', models.AutoField(primary_key=True, serialize=False)),
                ('folderName', models.CharField(max_length=31)),
                ('label', models.CharField(choices=[('None', 'None'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Red', 'Red'), ('Orange', 'Orange'), ('Grey', 'Grey'), ('Green', 'Green')], max_length=6)),
                ('shareCode', models.CharField(blank=True, max_length=255, null=True)),
                ('profileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collectionId', models.BigAutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('deltime', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('folderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.folder')),
                ('profileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SharedFolderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.folder')),
                ('profileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.profile')),
            ],
            options={
                'unique_together': {('profileId', 'folderId')},
            },
        ),
        migrations.CreateModel(
            name='CollectionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.collection')),
                ('tagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.tag')),
            ],
            options={
                'unique_together': {('collectionId', 'tagId')},
            },
        ),
    ]
