# Generated by Django 3.2.23 on 2024-05-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_rename_profilename_profile_profile name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile Name',
            new_name='profileName',
        ),
    ]
