# Generated by Django 3.2.23 on 2024-06-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_rename_profile name_profile_profilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='imgurl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
