# Generated by Django 4.2.13 on 2024-06-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_analys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
