# Generated by Django 4.2.13 on 2024-06-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_analys', '0002_note_author_note_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image_url',
            field=models.URLField(default='N/A'),
        ),
    ]
